name: First Workflow

on: workflow_dispatch

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello, GitHub Actions!"
      - name: Run multi-line thing
        run: |
          echo "Here's a directory structure"
          ls
          echo "there it was. See all the files."
      - name: Print goodbye
        run: echo "By y'all!"
